[package]
name = "snake"
version = "0.1.0"
authors = ["muasya <francismuasya@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
piston_window = "0.119.0"